FROM node:24-alpine

WORKDIR /app

# Копируем файлы зависимостей
COPY package.json yarn.lock ./
COPY .yarnrc.yml ./

# Устанавливаем зависимости
RUN yarn install --frozen-lockfile

# Копируем остальной код (но volumes перезапишут app, pages, public, components)
COPY . .

EXPOSE 3000

CMD ["yarn", "dev"]